name = "wallet-stats"
main = "./src/index.ts"
compatibility_date = "2023-05-18"

account_id = "<YOUR_ACCOUNT_ID_HERE>"
route = { pattern = "<YOUR_URL_HERE>", zone_id = "<YOUR_ZONE_ID_HERE>", custom_domain = true }

kv_namespaces = [
  { binding = "DEPOSITS", id = "<YOUR_KV_ID_HERE>", preview_id = "<YOUR_PREVIEW_KV_ID_HERE>" }
]
