name = "token-prices"
main = "./src/index.ts"
compatibility_date = "2023-05-18"

account_id = "<YOUR_ACCOUNT_ID_HERE>"
route = "<YOUR_URL_HERE>/*"

kv_namespaces = [
  { binding = "TOKEN_PRICES", id = "<YOUR_KV_ID_HERE>", preview_id = "<YOUR_PREVIEW_KV_ID_HERE>" },
  { binding = "TOKEN_ADDRESSES", id = "<YOUR_KV_ID_HERE>", preview_id = "<YOUR_PREVIEW_KV_ID_HERE>" }
]

[triggers]
crons = ["0 */2 * * *"]

[vars]
COVALENT_API_KEY = "<YOUR_API_KEY_HERE>"